check:
  - thoth-build
build:
  base-image: "quay.io/thoth-station/s2i-elyra-custom-notebook:v0.4.1"
  build-source-script: "image:///opt/app-root/builder"
  build-stratergy: Source
  registry: quay.io
  registry-org: thoth-station
  registry-project: datasets
  registry-secret: thoth-station-thoth-pusher-secret
